# Generated by Django 4.2.1 on 2023-06-13 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResutlModel',
            new_name='ResultModel',
        ),
    ]
